group = fr.euphyllia.tenseimc

# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion = 26.1.2
mcVersion = 26.1.2
channel = EXPERIMENTAL

canvasCommit = 7d1296b9b0fd2381201235ede90ab111f9247a21
# A commit hash from your repository 
# to fetch from in order to bring in objects for 3-way apply.
# Replace `Baguette` with your fork's name capitalized.
# oldBaguetteCommit = ba1486d1975a7cbe7bfc5bd5ecf6b5bc1ca4f668

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx4G
