name: Patch and Build

on:
  push:
    branches:
      - master

permissions: write-all
jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Permission gradlew
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyAllPatches --refresh-dependencies --stacktrace
      - name: Build
        run: ./gradlew clean --refresh-dependencies createMojmapPaperclipJar

      - name: Create Release
        if: github.event_name != 'pull_request'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.tag }}
          name: ${{ env.project_id_b }} - ${{ github.run_number }}
          body: |
            This release is automatically compiled by GitHub Actions
            ### Commit Message
            ${{ env.commit_msg }}
          artifacts: tensei-server/build/libs/*.jar
          generateReleaseNotes: true
          prerelease: ${{ github.ref_name == 'master' }}
          makeLatest: ${{ github.ref_name != 'master' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: false

env:
  tag: build-${{ github.ref_name }}-${{ github.run_number }}
  project_id_b: TenseiMC
  commit_id: ${{ github.sha }}
  commit_msg: ${{ github.event.head_commit.message }}
  pre: false
  make_latest: true